# Environment configuration settings for conda

name: trajectory-clustering
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23.5
  - scipy=1.10.1
  - matplotlib=3.6.2
  - similaritymeasures=1.1.0